; Maximum allowed size for uploaded files
upload_max_filesize = 50M

; Must be equal or bigger than upload_max_filesize
post_max_size = 50M

; Optional: increase max execution time for large uploads
max_execution_time = 300
max_input_time = 300
memory_limit = 256M

